### ISSUE TITLE
End stone

### ISSUE THREAD

**Issue by HoldYourWaffle** [Techern/Igneous-Extras#17]
Wouldn't it be nice to also add stairs/slabs/etc. made of end stone (and also the bricks in 1.9)?
Or doesn't that fit the Igneous title?

**Comment by CruzBishop** [comment]
[I was going to, but it looks like it'll be part of a separate mod :+1: ](https://github.com/Techern/End-Deco/issues)

Last time I started bringing prismarine and obsidian blocks into the one mod, it got out of hand, so I'll split it up a bit this time around :)

(Thanks again! I'll start work on it this afternoon or tonight)

**Comment by HoldYourWaffle** [comment]
Nice :)
I'll follow your project of couse (and translate it cause I can =])

**Comment by CruzBishop** [comment]
That's great, thank you! :D
