### ISSUE TITLE
Levers

### ISSUE THREAD

**Issue by CruzBishop** [Techern/Igneous-Extras#22]
- [ ] Smooth stone
- [ ] Diorite
- [ ] Andesite
- [ ] Granite
- [ ] Stone bricks

**Comment by HoldYourWaffle** [comment]
Isn't this a duplicate of #9?

**Comment by CruzBishop** [comment]
<sup><sup>Maybe I should sleep first</sup></sup>

Thanks >_<

**Comment by CruzBishop** [comment]
Closed as duplicate. D'oh

**Comment by HoldYourWaffle** [comment]
:joy:
