### ISSUE TITLE
Need to update to the new Forge Registry system

### ISSUE THREAD

**Issue by HoldYourWaffle** [Techern/Igneous-Extras#24]
Appearently `GameRegistry.registerItem(item, unlocalizedName)` is depreacated in the newer forge builds.
Needs a fix, cause a `@SuppressWarnings("deprecation")` isn't exactly a fix.

**Comment by CruzBishop** [comment]
Tried the following changes in local tree with no success:
- Added setRegistryName calls ("ignous_extras", "{blockName}") in constructors
- Replaced registerBlock with GameRegistry.register(block) for blocks with constructor changes
- Should register successfully, did not actually register, logging in results in no blocks

I was going to push it to a feature branch but ended up rage quitting and reset to HEAD :p

**Comment by CruzBishop** [comment]
It seems to be working when registering **both** the block and a new ItemBlock created from the block
