### ISSUE TITLE
Update to 1.9.4 (snapshots)

### ISSUE THREAD

**Issue by CruzBishop** [Techern/Igneous-Extras#27]
Includes a fix for #26 which allows completion of #11 

Should be done in a few hours

I really need to get back into this

**Comment by CruzBishop** [comment]
Done in develop, doing tools now

**Comment by CruzBishop** [comment]
Done :+1:

**Comment by HoldYourWaffle** [comment]
Noice (kindof slang way of typing nice here in NL). Friday I need to have a demo out for my school project, so after then I'll have more time for other stuff.

**Comment by CruzBishop** [comment]
Sounds good :D Good luck with your project, mate

**Comment by HoldYourWaffle** [comment]
Its funny because we havent got a name fir the game yet, so we just call it n00bject.
